import {makeStyles} from '@material-ui/core/styles';

export default makeStyles((theme) => ({
rectangle : {
    width:'460px',
    height: '546px',
    margin: '50px 0 18px 7px',
    padding: '100px 67px',
    boxShadow: '20px 20px 80px 0 rgba(2, 8, 22, 0.1)',
backgroundColor: '#ffffff',
    left: '140%',
    position: 'absolute',
    top: '-9%',
    [theme.breakpoints.down('xs')]: {
        position: 'revert',

    },
},
    been_able:{
        width: '296px',
        height: '78px',
        margin: '16px 0 20px',
        fontFamily: 'Roboto',
fontSize: '16px',
fontWeight: 'normal',
fontStretch: 'normal',
fontStyle: 'normal',
lineHeight: '1.63',
letterSpacing: '-0.33px',
textAlign: 'center',
color: '#595f6f'
    },
    again_arrow:{
        width: '97px',
        height: '16px',
        objectFit: 'contain',
        marginLeft: '-13%'
    },
error_div:{
    width: '460px',
    height: '494px',
    margin: '50px 0 49px 7px',
    padding: '100px 82px',
    boxShadow: '20px 20px 80px 0 rgba(2, 8, 22, 0.1)',
backgroundColor: '#ffffff',
    left: '140%',
    position: 'absolute',
    top: '-9%',
    [theme.breakpoints.down('xs')]: {
        position: 'revert',

    },
},
    try_btn:{
        width: '137px',
        height: '50px',
        margin: '50px 79px 0 80px',
        padding: '15px 4px 13px 53px',
        borderRadius: '5px',
boxShadow: '20px 20px 60px 0 rgba(0, 0, 0, 0.4)',
backgroundColor: '#ec1c24',
        '&:hover': {
            backgroundColor: '#ec1c24',
        },
    },
    try_txt:{
    whiteSpace: 'nowrap',
        width: '69px',
        height: '16px',
        fontFamily: 'Roboto',
fontSize: '16px',
fontWeight: '500',
fontStretch: 'normal',
fontStyle: 'normal',
lineHeight: '1',
letterSpacing: 'normal',
color:'#ffffff',
    },
    went_wrong:{
        width: '204px',
        height: '26px',
        margin: '20px 45.5px 20px 46.5px',
        fontFamily: 'Roboto',
fontSize: '20px',
fontWeight: 'bold',
fontStretch: 'normal',
fontStyle: 'normal',
lineHeight: 'normal',
letterSpacing: '-0.42px',
textAlign: 'center',
color: '#000000',
    },
    error:{
        width: '81px',
        height: '70px',
        margin: '-20px 117px 1px',
        padding: '0px',
        objectFit: 'contain',
        color:'#ec1c24',
    },
done:{
    width: '50px',
    height: '50px',
    margin: '0 138px 20px',
    objectFit: 'contain'
},
    your_inquiry:{
        width: '191px',
        height: '52px',
        margin: '20px 67px 20px 68px',
        fontFamily: 'Roboto',
fontSize:' 20px',
fontWeight: 'bold',
fontStretch: 'normal',
fontStyle: 'normal',
lineHeight: 'normal',
letterSpacing: '-0.42px',
textAlign: 'center',
color: '#000000'
    },
msg_sent:{
    width: '326px',
    height: '104px',
    margin: '20px 0 50px',
    fontFamily: 'Roboto',
fontSize: '16px',
fontWeight: 'normal',
fontStretch: 'normal',
fontStyle: 'normal',
lineHeight: '1.63',
letterSpacing: '-0.33px',
textAlign: 'center',
color:'#595f6f'
},
send_another_btn:{
    width: '207px',
    height: '50px',
    margin: '0px 57px 0px 58px',
    padding: '12px 15px 19px 56px',
    borderRadius: '5px',
boxShadow: '20px 20px 60px 0 rgba(0, 0, 0, 0.4)',
backgroundColor: '#ec1c24',
    '&:hover': {
        backgroundColor: '#ec1c24',
    },
}    ,
    whiteArrow:{
        width: '100px',
        height: '20px',
        objectFit: 'contain',
        marginLeft:'-16px',
    },
send_another_txt:{
    width: '149px',
    height: '16px',
    fontFamily: 'Roboto',
fontSize: '16px',
fontWeight: '500',
fontStretch: 'normal',
fontStyle: 'normal',
lineHeight:'1',
letterSpacing: 'normal',
color: '#ffffff',
whiteSpace: 'nowrap'
}
}))